version: '3'

services:
  # Servicio para Traefik (Proxy inverso)
  traefik:
    image: traefik                                      # Imagen oficial de Traefik
    container_name: traefik                             # Nombre del contenedor
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      proxynet:
        ipv4_address: ${TRAEFIK_IP_ADDRESS}             # Variable de entorno para la dirección IP
    ports:
      - "${HTTP_PORT}:80"                               # Variable de entorno para el puerto HTTP
      - "${HTTPS_PORT}:443"                              # Variable de entorno para el puerto HTTPS
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}                    # Variable de entorno para el correo de Cloudflare
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}            # Variable de entorno para el token de Cloudflare
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${TRAEFIK_CONFIG_PATH}/traefik.yml:/traefik.yml:ro"           # Variable de entorno para el path de configuración
      - "${TRAEFIK_CONFIG_PATH}/acme.json:/acme.json"                  # Variable de entorno para el archivo acme
      - "${TRAEFIK_CONFIG_PATH}/config.yml:/config.yml:ro"             # Variable de entorno para el path de config
      - "${TRAEFIK_LOGS_PATH}:/logs/"                                  # Variable de entorno para el path de logs

networks:
  proxynet:
    name: proxynet
    ipam:
      driver: default
      config:
       - subnet: ${PROXYNET_SUBNET}                     # Variable de entorno para la subred
