version: "3"

services:
  # Servicio para WireGuard (VPN de fácil configuración)
  wg-easy:
    image: weejewel/wg-easy                   # Imagen oficial de wg-easy
    container_name: wireguard                 # Nombre del contenedor
    volumes:
      - {CONFIG_PATH}:/etc/wireguard  # Volumen para configuraciones de WireGuard
    ports:
      - "${WG_UDP_PORT}:51820/udp"             # Puerto UDP para WireGuard
      - "${WG_TCP_PORT}:51821/tcp"             # Puerto TCP para interfaz web de wg-easy
    restart: always                           # Reiniciar siempre que el contenedor se detenga
    environment:
      - WG_HOST=${WG_HOST}                    # Nombre del host para el servidor VPN
      - PASSWORD=${WG_PASSWORD}               # Contraseña para acceso a la interfaz web
      - WG_PORT=${WG_UDP_PORT}                # Puerto para conexiones VPN
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}      # DNS predeterminado para los clientes VPN
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}      # IPs permitidas para routing
    cap_add:
      - NET_ADMIN                            # Necesario para configurar interfaces de red
      - SYS_MODULE                           # Necesario para cargar módulos del kernel
    sysctls:
      - net.ipv4.ip_forward=1                # Permitir el reenvío de paquetes
      - net.ipv4.conf.all.src_valid_mark=1   # Necesario para iptables y WireGuard
