version: '3'

services:
  # Servicio para Vaultwarden (gestor de contraseñas de código abierto)
  vaultwarden:
    image: vaultwarden/server                            # Imagen oficial de Vaultwarden
    container_name: vaultwarden                          # Nombre del contenedor
    restart: always
    volumes:
      - "${VAULTWARDEN_CONFIG_PATH}:/data/"               # Ruta para almacenar datos y configuración
    ports:
      - "${VAULTWARDEN_PORT}:80"                          # Puerto para el servicio Vaultwarden
    environment:
      - DOMAIN=${VAULTWARDEN_DOMAIN}                      # Dominio para Vaultwarden
      - LOGIN_RATELIMIT_MAX_BURST=10                      # Número máximo de intentos de inicio de sesión en ráfaga
      - LOGIN_RATELIMIT_SECONDS=60                        # Intervalo de tiempo para limitar intentos de inicio de sesión
      - ADMIN_RATELIMIT_MAX_BURST=10                      # Número máximo de intentos de administración en ráfaga
      - ADMIN_RATELIMIT_SECONDS=60                        # Intervalo de tiempo para limitar intentos de administración
      - SENDS_ALLOWED=true                                # Permite enviar elementos compartidos
      - EMERGENCY_ACCESS_ALLOWED=true                     # Permite el acceso de emergencia
      - WEB_VAULT_ENABLED=true                            # Activa la bóveda web
      - SIGNUPS_ALLOWED=true                              # Permite registrarse
      - SIGNUPS_VERIFY=true                               # Verifica los registros
      - SIGNUPS_VERIFY_RESEND_TIME=3600                   # Tiempo para reenviar la verificación de registro
      - SIGNUPS_VERIFY_RESEND_LIMIT=5                     # Límite de veces que se puede reenviar la verificación
      - SMTP_HOST=${SMTP_HOST}                            # Host SMTP para enviar correos
      - SMTP_FROM=${SMTP_FROM}                            # Dirección de correo desde la que se envían los correos
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}                  # Nombre desde el que se envían los correos
      - SMTP_PORT=${SMTP_PORT}                            # Puerto SMTP
      - SMTP_USERNAME=${SMTP_USERNAME}                    # Nombre de usuario SMTP
      - SMTP_PASSWORD=${SMTP_PASSWORD}                    # Contraseña SMTP
      - SMTP_AUTH_MECHANISM="Login"                       # Mecanismo de autenticación SMTP

